services:
  backup:
    image: ghcr.io/tecnativa/docker-duplicity:latest
    init: true
    container_name: backup
    hostname: backup-service
    restart: unless-stopped
    environment:
      DST: "gdrive://doodba-duplicity@doodba-451021.iam.gserviceaccount.com/trilium/?myDriveFolderID=19a3ufxGpQgz974oh0XJybpllqAnOOdrc"
      GOOGLE_SERVICE_JSON_FILE: /etc/backup/service-account-key.json
      PASSPHRASE: ${BACKUP_PASSPHRASE}
      JOB_800_WHAT: |
        dup full $$SRC $$DST
        dup --force remove-older-than 2W $$DST
      # JOB_300 is preconfigured to do daily incremental backups
      JOB_800_WHEN: weekly
      CRONTAB_HOURLY: "0 * * * *"
      CRONTAB_DAILY: "0 3 * * *"
      CRONTAB_WEEKLY: "30 0 * * 2"
      TZ: America/Detroit
    volumes:
      - backup_cache:/root:z
      - trilium01-data:/mnt/backup/src/trilium01-data:z
      - trilium02-data:/mnt/backup/src/trilium02-data:z
      - trilium03-data:/mnt/backup/src/trilium03-data:z
      - ./secrets/service-account-key.json:/etc/backup/service-account-key.json

volumes:
  backup_cache:
  trilium01-data:
  trilium02-data:
  trilium03-data:


networks:
  default:
    driver_opts:
      encrypted: 1
  inverseproxy_shared:
    external: true

