
services:
  trilium02:
    # Optionally, replace `latest` with a version tag like `v0.90.3`
    # Using `latest` may cause unintended updates to the container
    image: ghcr.io/triliumnext/trilium:latest
    container_name: trilium02
    hostname: ${TRILIUM02_HOSTNAME}
    ports:
      - '8080'

    # Restart the container unless it was stopped by the user
    restart: unless-stopped
    # environment:
    #   - TRILIUM_DATA_DIR=/home/node/trilium-data

    networks:
      default:
      inverseproxy_shared:

    labels:
      traefik.enable: "true"
      traefik.http.routers.trilium02-secure.rule: Host(`${TRILIUM02_HOSTNAME}`)
      traefik.http.routers.trilium02-secure.entrypoints: web-main
      traefik.http.routers.trilium02-secure.tls: "true"
      traefik.http.routers.trilium02-secure.tls.certResolver: letsencrypt
      traefik.http.routers.trilium02-secure.service: trilium02-svc
      traefik.http.services.trilium02-svc.loadbalancer.server.port: 8080

    
    volumes:
      # This is where Trilium will store its data
      - trilium02-data:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


volumes:
  trilium02-data:


networks:
  default:
    driver_opts:
      encrypted: 1
  inverseproxy_shared:
    external: true